#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
"""
Differential / property-based tests for UDF transpilation (SPARK-54783).

These tests run a fixed set of small Python UDFs twice -- once with
``spark.sql.experimental.optimizer.transpilePyUDFS`` enabled (so the catalyst
transpiler in :mod:`pyspark.sql.transpile` rewrites them into native
expressions) and once without -- and assert that the two runs produce the
same results for inputs generated by Hypothesis.

The transpiler is intentionally minimal at this point so we expect this
suite to surface bugs (e.g. truthiness / NULL-handling mismatches between
Python's ``if x:`` semantics and SQL's ``CASE WHEN``). Failures here should
be treated as real correctness gaps in the transpiler, not as test bugs to
silence.

History of bugs this suite has caught (each since fixed in the transpiler
proper -- listed for context, not as expected failures):

* ``PLAN_VALIDATION_FAILED_RULE_IN_BATCH`` from the rewritten plan
  reporting ``VOID`` output type. Fixed by casting the rewritten
  expression to the UDF's declared return type.
* A truthiness / NULL leak: ``if test:`` was lowered as
  ``when(test, body).otherwise(when(~test, else))``, but ``~NULL`` is
  ``NULL`` so a ``None`` test fell through both branches and yielded
  ``NULL`` instead of the else value. Fixed by lowering as
  ``when(coalesce(test, lit(False)), body).otherwise(else)``.
* ``%`` semantic mismatch between Python (sign of divisor) and Spark
  SQL (sign of dividend), e.g. ``(-8 + 7) % 5 == 4`` in Python vs
  ``-1`` in Spark SQL. Fixed by lowering ``%`` as
  ``sign(b) * pmod(sign(b) * a, abs(b))``.

The suite is gated on two things, both required:

* the ``RUN_HYPOTHESIS`` env var must be present in the environment
  (its value doesn't matter, only its presence), and
* the ``hypothesis`` package must be installed.

If either gate is unmet the entire suite is skipped cleanly so it never
becomes a CI tax for folks who haven't opted in. A targeted GitHub Actions
workflow (``.github/workflows/build_python_transpile_hypothesis.yml``)
flips both gates on, but only fires on PRs that actually touch the
transpiler or this test file.

To run locally::

    pip install hypothesis
    RUN_HYPOTHESIS=1 \\
        python/run-tests --testnames pyspark.sql.tests.test_udf_transpile_hypothesis

Set ``RUN_HYPOTHESIS_MAX_EXAMPLES`` to override the per-test example count
(default 25, kept small because every example spins up a Spark job).
"""

import os
import unittest

from pyspark.sql import Row
from pyspark.sql.types import (
    BooleanType,
    LongType,
    StructField,
    StructType,
)
from pyspark.sql.udf import UserDefinedFunction
from pyspark.testing.sqlutils import ReusedSQLTestCase
from pyspark.testing.utils import have_package


_HYPOTHESIS_ENV = "RUN_HYPOTHESIS"
_have_hypothesis = have_package("hypothesis")
# Presence-based: any value (including empty) opts in. We just check for the
# key being in os.environ so e.g. `RUN_HYPOTHESIS= python ...` still counts.
_hypothesis_enabled = _HYPOTHESIS_ENV in os.environ
_skip_reason = (
    f"Set {_HYPOTHESIS_ENV} in the environment to run; hypothesis must also be installed."
)


if _have_hypothesis:
    from hypothesis import HealthCheck, given, settings, strategies as st

    _DEFAULT_MAX_EXAMPLES = int(os.environ.get("RUN_HYPOTHESIS_MAX_EXAMPLES", "25"))

    # Spark jobs are expensive so we keep the example count modest. The
    # ``function_scoped_fixture`` health check is suppressed because we
    # intentionally reuse the class-level SparkSession across examples.
    _hyp_settings = settings(
        max_examples=_DEFAULT_MAX_EXAMPLES,
        deadline=None,
        suppress_health_check=[HealthCheck.function_scoped_fixture],
    )

    # 64-bit signed range, kept clear of overflow so arithmetic in both
    # Python and Spark stays in the safe LongType range.
    _LONG_BOUND = 2**31 - 1
    _long_strategy = st.one_of(st.none(), st.integers(min_value=-_LONG_BOUND, max_value=_LONG_BOUND))
    _bool_strategy = st.one_of(st.none(), st.booleans())


# ---- The UDF templates we exercise --------------------------------------
#
# We keep these as module-level callables so that ``inspect.getsource`` works
# (the transpiler reads source via inspection). They are deliberately written
# the way a user would: idiomatic Python, including ``if x is not None``
# guards and bare ``if x:`` truthiness checks.


def plus_four(x):
    if x is not None:
        return x + 4


def plus_four_with_else(x):
    if x is not None:
        return x + 4
    else:
        return 0


def is_none_branch(x):
    if x is None:
        return -1
    else:
        return x


def truthy_bool_branch(x):
    # The transpiler currently mishandles ``if x:`` for nullable bool inputs:
    # Python treats ``None`` as falsy and takes the else branch, but a naive
    # SQL lowering can produce NULL. This test is the canonical regression.
    if x:
        return 1
    else:
        return 2


def add_then_mod(x):
    if x is not None:
        return (x + 7) % 5


# ----------------------------------------------------------------------------


@unittest.skipUnless(_have_hypothesis and _hypothesis_enabled, _skip_reason)
class UDFTranspileHypothesisTests(ReusedSQLTestCase):
    """Compare transpiled vs. interpreted Python UDF output on Hypothesis-generated inputs."""

    def _run(self, func, return_type, value, schema):
        """Run ``func`` as a UDF with transpilation on and off, return both rows."""
        df = self.spark.createDataFrame([Row(a=value)], schema=schema)

        with self.sql_conf({"spark.sql.experimental.optimizer.transpilePyUDFS": True}):
            transpiled_udf = UserDefinedFunction(func, return_type)
            # Sanity: we expect each of these templates to be transpilable.
            # If the transpiler bails out we still want the test to run (so
            # the comparison just degrades to interpreted-vs-interpreted),
            # but we surface it via a subTest message so it's visible.
            transpiled_present = bool(transpiled_udf.transpiled)
            transpiled_value = df.select(transpiled_udf("a")).collect()[0][0]

        with self.sql_conf({"spark.sql.experimental.optimizer.transpilePyUDFS": False}):
            interpreted_udf = UserDefinedFunction(func, return_type)
            interpreted_value = df.select(interpreted_udf("a")).collect()[0][0]

        return transpiled_value, interpreted_value, transpiled_present

    if _have_hypothesis:

        @_hyp_settings
        @given(value=_long_strategy)
        def test_plus_four_matches_python(self, value):
            schema = StructType([StructField("a", LongType(), nullable=True)])
            transpiled, interpreted, _ = self._run(plus_four, LongType(), value, schema)
            self.assertEqual(transpiled, interpreted, f"plus_four mismatch on {value!r}")

        @_hyp_settings
        @given(value=_long_strategy)
        def test_plus_four_with_else_matches_python(self, value):
            schema = StructType([StructField("a", LongType(), nullable=True)])
            transpiled, interpreted, _ = self._run(
                plus_four_with_else, LongType(), value, schema
            )
            self.assertEqual(
                transpiled, interpreted, f"plus_four_with_else mismatch on {value!r}"
            )

        @_hyp_settings
        @given(value=_long_strategy)
        def test_is_none_branch_matches_python(self, value):
            schema = StructType([StructField("a", LongType(), nullable=True)])
            transpiled, interpreted, _ = self._run(
                is_none_branch, LongType(), value, schema
            )
            self.assertEqual(
                transpiled, interpreted, f"is_none_branch mismatch on {value!r}"
            )

        @_hyp_settings
        @given(value=_bool_strategy)
        def test_truthy_bool_branch_matches_python(self, value):
            # Known fragile case: Python's ``if x:`` for ``x=None`` is False
            # and takes the else branch; the transpiler has to coalesce the
            # NULL test before the otherwise/else lowering or it'll return
            # NULL instead of the else value.
            schema = StructType([StructField("a", BooleanType(), nullable=True)])
            transpiled, interpreted, _ = self._run(
                truthy_bool_branch, LongType(), value, schema
            )
            self.assertEqual(
                transpiled, interpreted, f"truthy_bool_branch mismatch on {value!r}"
            )

        @_hyp_settings
        @given(value=_long_strategy)
        def test_add_then_mod_matches_python(self, value):
            schema = StructType([StructField("a", LongType(), nullable=True)])
            transpiled, interpreted, _ = self._run(
                add_then_mod, LongType(), value, schema
            )
            self.assertEqual(
                transpiled, interpreted, f"add_then_mod mismatch on {value!r}"
            )


class UDFTranspileHypothesisGatingTests(unittest.TestCase):
    """Smoke tests that always run, regardless of the env gate.

    These don't talk to Spark; they just verify the gating / skipping logic
    so a misconfigured environment doesn't silently skip everything forever.
    """

    def test_env_var_name_is_documented(self):
        # If we ever rename the env var, the docstring needs to follow.
        self.assertIn(_HYPOTHESIS_ENV, __doc__)

    def test_skip_reason_mentions_env_var(self):
        self.assertIn(_HYPOTHESIS_ENV, _skip_reason)


if __name__ == "__main__":
    from pyspark.testing import main

    main()
